env: "dev" # dev, prod
http_server:
  address: "localhost:5050"
database:
  username: "backend"
  host: "localhost"
  port: "5432"
  dbname: "Chat"
  sslmode: "disable"
llm:
  url: "http://localhost:5000/chat"