version: "3.9"

services:

  llm_server:
    build:
      context: ./LLMServerDev
      dockerfile: Dockerfile
    image: llm_server
    container_name: llm_server
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - chatnetwork

  backend:
    build:
      context: ./ChatBackend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    volumes:
      - ./config:/config
    ports:
      - "5050:5050"
    restart: unless-stopped
    networks:
      - chatnetwork

  database:
    image: postgres:15
    container_name: database
    command: postgres -c config_file=/etc/postgresql.conf && postgres -c hba_file=/etc/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./ChatDatabase/pg-init:/docker-entrypoint-initdb.d
      - ./ChatDatabase/pg-conf/postgresql.conf:/etc/postgresql.conf
      - ./ChatDatabase/pg-conf/pg_hba.conf:/etc/pg_hba.conf
    ports:
      - "5430:5432"
    expose:
      - 5432
    restart: unless-stopped
    networks:
      - chatnetwork

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 11111111
    # volumes:
    #   - minio-storage:/data
    restart: unless-stopped
    networks:
      - chatnetwork

networks:
  chatnetwork:
    driver: bridge