version: "3.9"

services:

  llm:
    build:
      context: ./ChatLLM/dev
      dockerfile: Dockerfile
    image: llm
    container_name: llm
    expose:
      - 50100
    restart: unless-stopped
    networks:
      - chatnetwork

  audio:
    build:
      context: ./ChatAudio/dev
      dockerfile: Dockerfile
    image: audio
    container_name: audio
    expose:
      - 50200
    restart: unless-stopped
    networks:
      - chatnetwork

  video:
    build:
      context: ./ChatVideo/dev
      dockerfile: Dockerfile
    image: video
    container_name: video
    expose:
      - 50300
    restart: unless-stopped
    networks:
      - chatnetwork

  rag:
    build:
      context: ./ChatRAG/dev
      dockerfile: Dockerfile
    image: rag
    container_name: rag
    expose:
      - 50400
    restart: unless-stopped
    networks:
      - chatnetwork

  backend:
    build:
      context: ./ChatBackend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    volumes:
      - ./config:/config
    ports:
      - "5050:5050"
    environment:
      - CONFIG_PATH=/config/backend.config.dev.yml
    restart: unless-stopped
    networks:
      - chatnetwork

  database:
    image: postgres:15
    container_name: database
    command: postgres -c config_file=/etc/postgresql.conf && postgres -c hba_file=/etc/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./ChatDatabase/pg-init:/docker-entrypoint-initdb.d
      - ./ChatDatabase/pg-conf/postgresql.conf:/etc/postgresql.conf
      - ./ChatDatabase/pg-conf/pg_hba.conf:/etc/pg_hba.conf
    expose:
      - 5432
    restart: unless-stopped
    networks:
      - chatnetwork

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 11111111
      MINIO_SERVER_ADDRESS: "0.0.0.0:9000"
    restart: unless-stopped
    networks:
      - chatnetwork

networks:
  chatnetwork:
    driver: bridge