version: "3.9"

services:

  audio:
    image: audio:latest
    container_name: audio
    expose:
      - 50200
    volumes:
      - audio:/audio/audio #<---
    environment:
      - CONFIG_PATH=/audio/audio/config.yaml
    restart: unless-stopped
    networks:
      - chatnetwork

  video:
    image: video:latest
    container_name: video
    expose:
      - 50300
    volumes:
      - video:/video/video #<---
    environment:
      - MINIO_USER=minio
      - MINIO_PASSWORD=11111111
      - CONFIG_PATH=/video/video/config.yaml
    restart: unless-stopped
    networks:
      - chatnetwork

  rag:
    image: rag:latest
    container_name: rag
    expose:
      - 50400
    volumes:
      - rag:/rag/rag #<---
    environment:
      - CONFIG_PATH=/rag/rag/config.yaml
    restart: unless-stopped
    networks:
    - chatnetwork

  frontend: #<---
    image: frontend:latest
    container_name: frontend 
    ports:
      - "8080:8080" #<---
    restart: unless-stopped
    networks:
      - chatnetwork

  backend:
    image: backend:latest
    container_name: backend
    volumes:
      - config:/config #<---
    expose:
      - 5050
    environment:
      - CONFIG_PATH=/config/backend.config.prod.yml
    restart: unless-stopped
    networks:
      - chatnetwork

  database:
    image: postgres:15
    container_name: database
    command: postgres -c config_file=/etc/postgresql.conf && postgres -c hba_file=/etc/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg-init:/docker-entrypoint-initdb.d #<---
      - pg-conf/postgresql.conf:/etc/postgresql.conf #<---
      - pg-conf/pg_hba.conf:/etc/pg_hba.conf #<---
    expose:
      - 5432
    restart: unless-stopped
    networks:
      - chatnetwork

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 11111111
    restart: unless-stopped
    networks:
      - chatnetwork

networks:
  chatnetwork:
    driver: bridge