version: "3.9"

services:

  llm_server:
    build:
      context: ./LLMServerDev
      dockerfile: Dockerfile
      args:
        GOOS: linux
    image: llm_server
    container_name: llm_server
    restart: unless-stopped

    backend:
      build:
        context: ./ChatBackend
        dockerfile: Dockerfile
        args:
          GOOS: linux
      image: backend
      container_name: backend
      ports:
        - "5050:5050"
      restart: unless-stopped
      depends_on:
        - llm_server