version: "3.9"

services:

  llm:
    build:
      context: ./LLMServer
      dockerfile: Dockerfile
    image: llm
    container_name: llm
    expose:
      - 50100
    restart: unless-stopped
    networks:
      - chatnetwork

  backend:
    build:
      context: ./ChatBackend
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    volumes:
      - ./config:/config
    ports:
      - "5050:5050"
    environment:
      - CONFIG_PATH=/config/backend.config.dev.yml
    restart: unless-stopped
    networks:
      - chatnetwork

  database:
    image: postgres:15
    container_name: database
    command: postgres -c config_file=/etc/postgresql.conf && postgres -c hba_file=/etc/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./ChatDatabase/pg-init:/docker-entrypoint-initdb.d
      - ./ChatDatabase/pg-conf/postgresql.conf:/etc/postgresql.conf
      - ./ChatDatabase/pg-conf/pg_hba.conf:/etc/pg_hba.conf
    expose:
      - 5432
    restart: unless-stopped
    networks:
      - chatnetwork

networks:
  chatnetwork:
    driver: bridge