version: "3.9"

services:

  llm_server:
    build:
      context: ./LLMServerDev
      dockerfile: Dockerfile
      args:
        GOOS: $GOOS
    image: llm_server
    container_name: llm_server
    ports:
        - "5000:5000"
    restart: unless-stopped

  # backend:
  #   build:
  #     context: ./ChatBackend
  #     dockerfile: Dockerfile
  #     args:
  #       GOOS: $GOOS
  #   image: backend
  #   container_name: backend
  #   ports:
  #     - "5050:5050"
  #   restart: unless-stopped
  #   depends_on:
  #     - llm_server
  #     - database

  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./ChatDatabase:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped