version: "3"

tasks:
  generate-audio:
    cmds:
      - python3 -m grpc_tools.protoc -I ./protos/ ./protos/audio.proto --python_out=./ChatAudio --grpc_python_out=./ChatAudio --pyi_out=./ChatAudio
      - protoc -I ./protos/ ./protos/audio.proto --go_out=./ChatBackend/gen/audio --go_opt=paths=source_relative --go-grpc_out=./ChatBackend/gen/audio --go-grpc_opt=paths=source_relative
  generate-auth:
    cmds:
      - protoc -I ./protos/ ./protos/auth.proto --go_out=./Auth/gen --go_opt=paths=source_relative --go-grpc_out=./Auth/gen --go-grpc_opt=paths=source_relative
      - protoc -I ./protos/ ./protos/auth.proto --go_out=./ChatBackend/gen/auth --go_opt=paths=source_relative --go-grpc_out=./ChatBackend/gen/auth --go-grpc_opt=paths=source_relative
  generate-llm:
    cmds:
      - python3 -m grpc_tools.protoc -I ./protos/ ./protos/llm.proto --python_out=./LLMServer --grpc_python_out=./LLMServer --pyi_out=./LLMServer
      - protoc -I ./protos/ ./protos/llm.proto --go_out=./ChatBackend/gen/llm --go_opt=paths=source_relative --go-grpc_out=./ChatBackend/gen/llm --go-grpc_opt=paths=source_relative
