env: "dev-linux" # dev-linux / dev-windows / prod
http_server:
  address: ":5050"
database:
  username: "backend"
  password: "f*c$;d3EQACG8KW"
  host: "localhost"
  port: "5430"
  dbname: "Chat"
  sslmode: "disable"
llm:
  address: "localhost:50100"
  history_limit: 15
  max_tokens: 1024
audio:
  address: "localhost:50200"
video:
  address: "localhost:50300"
rag:
  address: "localhost:50400"
minio:
  address: "localhost:9000"
  user: "minio"
  password: "11111111"