# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'video.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x05video\"\x1b\n\x0cVideoRequest\x12\x0b\n\x03URI\x18\x01 \x01(\t\"#\n\rVideoResponse\x12\x12\n\nobjectName\x18\x01 \x01(\t2C\n\x0cVideoService\x12\x33\n\x06\x44\x65tect\x12\x13.video.VideoRequest\x1a\x14.video.VideoResponseB\x1aZ\x18MMaxaMM.video.v1;videov1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030MMaxaMM.video.v1;videov1'
  _globals['_VIDEOREQUEST']._serialized_start=22
  _globals['_VIDEOREQUEST']._serialized_end=49
  _globals['_VIDEORESPONSE']._serialized_start=51
  _globals['_VIDEORESPONSE']._serialized_end=86
  _globals['_VIDEOSERVICE']._serialized_start=88
  _globals['_VIDEOSERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
