env: "dev-linux" # dev-linux / dev-windows / prod
http_server:
  address: ":5050"
database:
  username: "backend"
  host: "database"
  port: "5432"
  dbname: "Chat"
  sslmode: "disable"
llm:
  url: "http://llm_server:5000/chat"
  history_limit: 15
  max_tokens: 1024